#-------------------------------
# General Site Settings

title: Luís Moura
description: Thinker // Programmer // Idiot
email: luisppmoura@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me,  url: '#about-me'}
- {name: Work,      url: '#work'}
- {name: References,   url: '#clients'}
- {name: Contact,   url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Hire Backend programmer. Java, Python, C#'
  rel-author: ''
  rel-publisher: ''

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  Having worked in such different areas as Acting, Teaching, Sales, Recruiting, 
  Marketing, Team Leading, and being an active teenager that founded a Youth Group, 
  was a Boy Scout, Musician and Choir Leader, one might ask ”why Computer 
  Science now?”. I believe that my background allowed me to be flexible, a real 
  strategist, and a problem solver. Having to master different skills demanded 
  organization and lots of spreadsheets with algorithms to manage projects and 
  my evolution. Eventually, programming and developing systems or even better 
  putting them to the test became not only a necessity but a passion.
  
  Now, after 2 years of experience with great people in the Quality Assurance 
  area, I developed not only the necessary competencies but also a drive to 
  keep pushing the team for better quality standards, the resourcefulness to 
  trace the plan to ensure those standards, and hunger for developing better 
  test automation and highly productive team processes.


skills:
- {name: JAVA, value: '9'}
- {name: Python, value: '8'}
- {name: 'C, C++, C#', value: '6'}
- {name: JUnit, value: '9'}
- {name: Selenium, value: '8'}
- {name: Cucumber, value: '8'}
- {name: Communication, value: '9'}
- {name: Organization, value: '8'}
- {name: Learning, value: '10'}
#- {name: Programming, value: '8'}


#-------------------------------
# Work Section

projects:
- {name: Feedzai´s Anti-money Laundering Rules Test Template, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: The Units Project, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: The Potatoes Project, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: The Cheddar Project (Pac-Man), folder: 'proj-3', file: 'work/proj-3.html'}
- {name: The Blueberry Project (BlueBudget), folder: 'proj-4', file: 'work/proj-4.html'}



#-------------------------------
# Clients Section

clients:
- {avatar: 'face1.jpg',
  name: 'Maria Lavoura',
  title: 'Friend and University classmate',
  quote: '<p><strong>Luis has a great capacity for understanding new concepts 
  and for transmitting knowledge.</strong> In the university, he was the one 
  everyone used to ask questions to.</p>',
  logo: 'logo1.png'}
- {avatar: 'face2.png',
  name: 'Miguel Oliveira e Silva',
  title: 'Professor at Universidade de Aveiro',
  quote: '<p><strong>It was an enormous pleasure to have Luís as a student.</p>',
  logo: 'logo2.png'}


#-------------------------------
# Contact Section

social:
#- {icon: 'twitter', link: 'http://twitter.com/devtipsshow'}
#- {icon: 'dribbble', link: 'https://dribbble.com/travisneilson'}
#- {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
#- {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
- {icon: 'icon-linkedin', link: 'https://www.linkedin.com/in/luispedromoura/'}
- {icon: 'icon-github', link: 'https://github.com/LuisPedroMoura/'}
- {icon: 'fab fa-hackerrank', link: 'https://www.hackerrank.com/luisppmoura/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
