#-------------------------------
# General Site Settings

title: Luís Moura
description: Thinker // Programmer // Idiot
email: luisppmoura@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me,  url: '#about-me'}
- {name: Work,      url: '#work'}
- {name: References,   url: '#clients'}
- {name: Contact,   url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Hire Backend programmer. Java, Python, C#'
  rel-author: ''
  rel-publisher: ''

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  Having worked in such different areas as Acting, Teaching, Sales, Recruiting, Marketing, Team Leading,
  and being an active teenager that founded a Youth Group, was a Boy Scout, Musician and Chorus Leader,
  one might ask "why Computer Science?". I believe that my background allowed me to be flexible,
  a real strategist and a problem solver.
  Having to master different skills demanded organization and lots of spreadsheets with algorithms to manage projects
  and my own evolution. Eventually, programming and developing systems became not only a necessity, but a passion.


skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '8'}
- {name: Learning, value: '10'}
#- {name: Programming, value: '8'}
- {name: JAVA, value: '8'}
- {name: Python, value: '8'}
- {name: 'C, C++, C#', value: '6'}

#-------------------------------
# Work Section

projects:
- {name: The Units Project, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: The Potatoes Project, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: The Cheddar Project (Pac-Man), folder: 'proj-3', file: 'work/proj-3.html'}
- {name: The Blueberry Project (BlueBudget), folder: 'proj-4', file: 'work/proj-4.html'}
#- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
#- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
#- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face3.jpg',
  name: 'Maria Lavoura',
  title: 'Amiga e Engenheira Informática',
  quote: '<p><strong>O Luís é um individuo que não são dois.</strong> É metade. Um verdadeiro banano!</p>',
  logo: 'logo1.png'}
- {avatar: 'face-atariboy.jpg',
  name: 'Hank McCoy',
  title: 'Eater of Salad, Antartica Int.',
  quote: '<p><strong>Working with Travis was the highlight of my career.</strong> Other moments of note were collecting the largest number of paperclips in the office, and winning a trophy for saying "uh huh, and then what?" 30 times in a row to my girlfriend without her noticing.</p>',
  logo: 'logo2.png'}
- {avatar: 'face-jackiesaik.jpg',
  name: 'Stacy Lang',
  title: 'Social Media Girl, Quebec Int.',
  quote: '<p><strong>Yea, I guess hes good at computers or something,</strong> but let me ask you this: If a cat always lands on its feet, and buttered bread always lands butter side down, what would happen if you tied buttered bread on top of a cat?</p>',
  logo: 'logo3.png'}
- {avatar: 'face-teleject.jpg',
  name: 'Cleatus Cassidy',
  title: 'VP of Helmut, Lorem Sorem LLC.',
  quote: '<p><strong>Back in old country</strong> only nerds who is playing on computers. Now all bros is wanting to make codes and junk. I lost foot in war. You dont see girls asking me about homework.</p>',
  logo: 'logo4.png'}


#-------------------------------
# Contact Section

social:
#- {icon: 'twitter', link: 'http://twitter.com/devtipsshow'}
#- {icon: 'dribbble', link: 'https://dribbble.com/travisneilson'}
#- {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
#- {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
- {icon: 'icon-linkedin', link: 'https://www.linkedin.com/in/luispedromoura/'}
- {icon: 'icon-github', link: 'https://github.com/LuisPedroMoura/'}
- {icon: 'fab fa-hackerrank', link: 'https://www.hackerrank.com/luisppmoura/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
